version: '3.8'

services:
  app:
    image: 'dockersevinch02/online-food-store-app:1'
    build:
      context: .
    container_name: online-food-store-app
    depends_on:
      - postgres
      - redis
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/food_store
       - DB_USERNAME=postgres
       - DB_PASSWORD=root123
       - REDIS_HOST=redis
       - REDIS_PORT=6379


    ports:
      - "9001:8080"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=food_store
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
