server:
  port: 8080

#DATABASE
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/food_store}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root123}
    hikari:
      maximum-pool-size: 10
#REDIS
redis:
  cache:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    caches:
      categories: 15
      products: 30
      users: 30

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#LOG
logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: log.log

#SWAGGER
springfox:
  documentation:
    swagger-ui:
      enabled: true